# from dash import dcc, html
# import dash_bootstrap_components as dbc



# layout=dbc.Container([
#         html.Div([
#             dbc.Row([
#                 dbc.Col(html.H2("AI Generated Text Checker"),
#                 className="header_title"
#                 ),
#             ]),
#             dbc.Row([
#                 dbc.Col(html.P(
#                     children="""Classify the text generated by AI tools like chatGPT.
#                     Fake refers to the text generated by an AI and Real refers to the text written
#                     by a human.""",
#                     ),
#                 className="header_description"),
#             ]),
#         ], className='header'),
#         html.Div([
#             dbc.Row([
#                 dbc.Col(dbc.Textarea(
#                     id='text',
#                     placeholder="Enter Text Here",
#                     style={'width': '100%', 'height': 400},
#                 ), width={"size": 6, "offset": 3}),
#             ]),
#             dbc.Row(
#             [
#                 dbc.Col([
#                     dcc.Upload(id='upload_file', children=[
#                                 'Upload File ',
#                                 html.A('(.txt, .docx, .pdf)'), 
#                     ], multiple=False,
#                         className='upload-style')
#                 ], width={"size": 6, "offset": 3}),
#             ],
#             ),
#             dbc.Row([
#                 dbc.Col(html.H5('Real', className="text-info"), width=4, style={'text-align' : 'right'}),
#                 dbc.Col(dcc.Loading(id='loading',children=html.Div(''),
#                     type="default"),
#                     width=4),
#                 dbc.Col(html.H5('Fake', className="text-danger"), width=4, style={'text-align' : 'left'}),
#             ], style={'margin-top' : '20px'}),
#             dbc.Row([
#                 dbc.Col(dbc.Progress(
#                 [
#                     dbc.Progress(id="real_prog", value=50, color="info", bar=True),
#                     dbc.Progress(id="fake_prog", value=50, color="danger", bar=True),
#                 ], style={'height' : '25px', 'font-size' : '16px'}
#                 ), width={"size": 6, "offset": 3}),
#             ]),
#         ], className='card'),
#     ])


from dash import dcc, html
import dash_bootstrap_components as dbc

layout = dbc.Container([
    html.Div([
        html.H1("AI Text Checker", className="display-4 text-primary mt-5 mb-4"),
        html.P(
            "Classify text generated by AI tools like chatGPT. "
            "Distinguish between AI-generated (Fake) and human-written (Real) text.",
            className="lead text-muted"
        ),
    ], className='jumbotron text-center bg-light p-4 rounded'),

    html.Div([
        dbc.Row([
            dbc.Col(
                dcc.Textarea(
                    id='text',
                    placeholder="Enter Text Here",
                    style={'width': '100%', 'height': 200},
                    className="form-control shadow-none"
                ),
                width=8, lg={"size": 6, "offset": 2}
            ),
        ], className="mb-4"),

        dbc.Row([
            dbc.Col(
                dcc.Upload(
                    id='upload_file',
                    children=[
                        dbc.Button("Upload File", color="primary", className="mr-2"),
                        html.Span("(.txt, .docx, .pdf)", className="text-muted"),
                    ],
                    multiple=False,
                    className='custom-file-upload'
                ),
                width=8, lg={"size": 6, "offset": 2}
            ),
        ], className="mb-4"),

        dbc.Row([
            dbc.Col(html.H5('Real', className="text-info"), width=4, style={'text-align': 'right'}),
            dbc.Col(dcc.Loading(id='loading', children=html.Div(''), type="default"), width=4),
            dbc.Col(html.H5('Fake', className="text-danger"), width=4, style={'text-align': 'left'}),
        ], style={'margin-top': '20px'}),

        dbc.Row([
            dbc.Col(dbc.Progress(
                [
                    dbc.Progress(id="real_prog", value=50, color="info", bar=True),
                    dbc.Progress(id="fake_prog", value=50, color="danger", bar=True),
                ], style={'height': '25px', 'font-size': '16px'}
            ), width=8, lg={"size": 6, "offset": 2}),
        ]),
    ], className='container rounded shadow p-4 mb-5 bg-white'),
], fluid=True)
